### ISSUE TITLE
Arrays missing values if the values don't follow each other in the XML

### ISSUE THREAD

**Issue by actongate** [VFPX/nfXML#1]
The following XML which results in an array only includes the last two values ...

`<specification>
        <type>value 1</type>
        <type>value 2</type>
        <pitch>2</pitch>
        <type>value 3</type>
        <type>value 4</type>
</specification>`

Having looked it seems to rely on the previous node name being the same else when it hits the third <type> tag it recreates the array.

**Comment by nfoxdev** [comment]
Hi, thanks for your report.
Indeed it was unexpected to have non-contiguous array siblings. Will make the update to check if property already exists; if it does and it's not an array, it will be automatically converted to array.

**Comment by nfoxdev** [comment]
Fixed. 👍
